version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: rulewise-server
    working_dir: /RuleWise
    environment:
      - PORT=$PORT
      - MONGO_URL=$MONGO_URL
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rulewise-client
    working_dir: /RuleWise
    environment:
      - VITE_BASE_URL=$VITE_BASE_URL
    ports:
      - $VITE_LOCAL_PORT:$VITE_DOCKER_PORT
    depends_on:
      - server
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: rulewise-nginx
    restart: always
    ports:
      - $NGINX_LOCAL_PORT:$NGINX_DOCKER_PORT
    networks:
      - app-network
    depends_on:
      - server
      - client

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
